name: "Build"
on:
  workflow_dispatch:
  push:

env:
  IMAGE_NAME: shonkblog
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-container-image:
    name: "Build Container Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Podman and Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y podman buildah
      - name: Build image
        run: |
          buildah build -t ${{ env.IMAGE_NAME }}:upload -f Containerfile .
      - name: Save image as file
        run: podman image save ${{ env.IMAGE_NAME }}:upload -o image.tar
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-image
          path: image.tar
          retention-days: 1

  upload:
    name: "Upload image to ghcr"
    runs-on: ubuntu-latest
    needs: [build-container-image]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Imagefile
        uses: actions/download-artifact@v4
        with:
          name: container-image
      - name: Load image
        run: podman load -i image.tar
      - name: Login Podman to ghcr.io
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          podman push ${{ env.IMAGE_NAME }}:upload ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          REF_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          podman push ${{ env.IMAGE_NAME }}:upload ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${REF_NAME}
          if [ "${{ github.ref_name }}" == "main" ]; then
            podman push ${{ env.IMAGE_NAME }}:upload ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          fi
